fixes

diff --git a/.github/workflows/document.yml b/.github/workflows/document.yml
--- a/.github/workflows/document.yml
+++ b/.github/workflows/document.yml
@@ -3,7 +3,7 @@ name: Update Documentation with API Data
 on:
   push:
     branches:
-    - main # Trigger on commits to the main branch
+    - main
 
 jobs:
   call-api-and-update-documentation:
@@ -56,13 +56,22 @@ jobs:
           '{repo_owner: $repo_owner, repo: $repo, files_changed: $files_changed}')
         echo "JSON Payload: $json_payload"  # Debugging step
         response=$(curl -s https://docubot-two.vercel.app/document -H "Content-Type: application/json" -d "$json_payload")
+        if [ $? -ne 0 ]; then
+          echo "Error in API request"
+          exit 1
+        fi
         echo "API Response: $response"  # Debugging step
-        response_content=$(echo $response | jq -r '.updated_doc')
-        echo "$response_content" > response.txt
+        if echo "$response" | jq -e . > /dev/null 2>&1; then
+          response_content=$(echo $response | jq -r '.updated_doc')
+          echo "$response_content" > response.txt
+        else
+          echo "Invalid JSON response: $response"
+          exit 1
+        fi
 
     - name: Update Documentation
       run: |
-        echo "$response_content" > documentation.md
+        cat response.txt > documentation.md
 
     - name: Commit and push changes
       run: |
